CREATE TABLE IF NOT EXISTS Pokemon  (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Nombre TEXT, 
Nivel INTEGER  NOT  NULL, 
Habilidad TEXT , 
Genero TEXT, 
RutaP INTEGER);

CREATE TABLE IF NOT EXISTS Tipo ( 
Id INTEGER UNIQUE PRIMARY KEY,
Nombre TEXT);

CREATE TABLE IF NOT EXISTS "Pokemon _Tipo" (
IdPokemon INTEGER,
IdTipo INTEGER,
FOREIGN KEY (IdTipo) REFERENCES Tipo,
FOREIGN KEY (IdPokemon) REFERENCES Pokemon,
PRIMARY KEY (IdPokemon, IdTipo));

CREATE TABLE IF NOT EXISTS Entrenador (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY ,
Genero TEXT,
Nombre TEXT
);

CREATE TABLE IF NOT EXISTS Centro (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY ,
Trabajadores TEXT,
Ciudad TEXT
);

CREATE TABLE IF NOT EXISTS "Entrenador_Centro" (
IdEntrenador INTEGER,
IdCentro INTEGER,
FOREIGN KEY (IdEntrenador) REFERENCES Entrenador,
FOREIGN KEY (IdCentro) REFERENCES Centro,
PRIMARY KEY (IdEntrenador, IdCentro));

CREATE TABLE IF NOT EXISTS "Entrenador_Pokemon" (
IdPokemon INTEGER,
IdEntrenador INTEGER,
Cantidad INTEGER,
FOREIGN KEY (IdPokemon) REFERENCES Pokemon,
FOREIGN KEY (IdEntrenador) REFERENCES Entrenador,
PRIMARY KEY (IdPokemon, IdEntrenador)
);

CREATE TABLE IF NOT EXISTS Ruta (
Id INTEGER NOT NULL PRIMARY KEY,
Nombre INTEGER
);