INSERT INTO Ruta ( Nombre) VALUES
("Ruta 1"),
("Ruta 2"),
("Ruta 3"),
("Ruta 4"),
("Ruta 5"),
("Ruta 6"),
("Ruta 7"),
("Ruta 8"),
("Ruta 9"),
("Ruta 10"),
("Ruta 11");

INSERT INTO Centro (Trabajadores, Ciudad) VALUES
("Joy 1", "Carmin"),
("Joy 2,", "Azafran"),
("Joy 3", "Azulona"),
("Joy 4", "Verde"),
("Joy 5", "Fuscia"),
("Joy 6", "Canela"),
("Joy 7", "Plateada");

INSERT INTO Entrenador (Genero, Nombre) VALUES
("Masculino", "Ash"),
("Femenino", "Misty"),
("Masculino", "Brock"),
("Masculino", "Blaine");

INSERT INTO Tipo ( Nombre) VALUES
("Agua"),                           
("Fuego"),                          
("Electrico"),                      
("Normal"),                         
("Tierra"),  
("Dragon"),                         
("Volador"),                        
("Hielo"),                          
("Lucha"),                          
("Bicho"),                          
("Psiquico"),                       
("Fantasma"),                       
("Veneno"),                         
("Planta"),                         
("Roca"),                               
("Acero");       


INSERT INTO Pokemon (Nombre, Nivel, Habilidad, Genero,  RutaP) VALUES
("Bulbasaur", 3, "Espesura", "M", 1),
("Ivysaur", 5, "Espesura", "M", 1),
("Venosaur", 7, "Espesura", "M", 1),
("Charmander", 3, "Mar Llamas", NULL, 2),
("Charmeleon", 5, "Mar Llamas", NULL, 2),
("Charizard", 7, "Mar Llamas", NULL, 2),
("Squirtle", 6, "Torrente", "M", 4),
("Wartortle", 8, "Torrente", "M", 4),
("Blaistoise", 9, "Torrente", "M", 4),
("Caterpie", 1, "Polvo Escudo", "F", 6),
("Metapod", 3, "Mudar", NULL, 6),
("Butterfree", 5, "Ojo Compuesto", NULL, 6),
("Pidgey", 5, "Tumbos", NULL, 7),
("Pidgeotto", 6, "Tumbos", NULL, 7),
("Pidgeot", 8, "Tumbos", NULL, 7),
("Ekans", 5, "Mudar", "F", 8),
("Arbok", 5, "Mudar", "M", 8),
("Pikachu", 9, "Electricidad Estatica", NULL, 9),
("Raichu", 8, "Electricidad Estatica", NULL, 9),
("Evee", 2, "Fuga", NULL, 3),
("Geodude", 5, " Cabeza Roca", "F", 10),
("Graveler", 6, " Cabeza Roca", "F", 10),
("Golem", 7, " Cabeza Roca", NULL, 10),
("Dratini", 5, "Mudar", NULL, 11),
("Dragonair", 6, "Mudar", NULL, 11),
("Dragonite", 7, "Mudar", NULL, 11),
("Machop", 2, "Agallas", "M", 1),
("Machoke", 3, "Agallas", NULL, 1),
("Machamp", 4, "Agallas", NULL, 1),
("Abra", 5, "Sincronia", NULL, 2),
("Kadabra", 6, "Sincronia", NULL, 2),
("Alakazam", 7, "Sincronia", "F", 2),
("Mewtwo", 9, "Presion", NULL, 1),
("Mew", 9, "Sincronia", NULL, 1),
("Gastly", 3, "Levitacion", NULL, 1),
("Haunter", 4, "Levitacion", "M", 1),
("Gengar", 5, "Cuerpo Maldito", NULL, 1),
("Magnemite", 3, "Iman", NULL, 1),
("Magneton", 4, "Iman", "F", 1),
("Voltorb", 6, "Insonorizar", NULL, 1),
("Electrode", 7, "Insonorizar", NULL, 1),
("Exeggcute", 8, "Clorofila", "M", 1),
("Exeggutor", 9, "Clorofila", "F", 1),
("Lapras", 3, "Caparazon", NULL, 7);


INSERT INTO "Pokemon _Tipo" ( IdPokemon, IdTipo) VALUES
(1, 14),
(1, 13),
(2, 13),
(2, 14),
(3, 14),
(3, 13),
(4, 2),
(5, 2),
(6, 7),
(6, 2),
(7, 1),
(8, 1),
(9, 1),
(10, 10),
(11, 10),
(12, 10), 
(12, 7),
(13, 4),
(13, 7),
(14, 4),
(14, 7),
(15, 4),
(15, 7),
(16, 13),
(17, 13),
(18, 3),
(19, 3),
(20, 4),
(21, 15),
(21, 5),
(22, 15),
(22, 5),
(23, 15),
(23, 5),
(24, 6),
(25, 6),
(26, 6),
(26, 7),
(27, 9),
(28, 9),
(29, 9),
(30, 11),
(31, 11),
(32, 11),
(33, 11),
(34, 11),
(35, 12),
(35, 13),
(36, 12),
(36, 13),
(37, 12),
(37, 13),
(38, 16),
(38, 3),
(39, 16),
(39, 3),
(40, 3),
(41, 3),
(42, 14),
(42, 11),
(43, 14),
(43, 11),
(44, 1),
(44, 8);


