INSERT INTO Pokemon (Nombre, Nivel, Habilidad, Genero,  RutaP) VALUES
("Bulbasaur", 3, "Espesura", "M", 1),
("Ivysaur", 5, "Espesura", "M", 1),
("Venosaur", 7, "Espesura", "M", 1),
("Charmander", 3, "Mar Llamas", NULL, 2),
("Charmeleon", 5, "Mar Llamas", NULL, 2),
("Charizard", 7, "Mar Llamas", NULL, 2),
("Squirtle", 6, "Torrente", "M", 4),
("Wartortle", 8, "Torrente", "M", 4),
("Blaistoise", 9, "Torrente", "M", 4),
("Caterpie", 1, "Polvo Escudo", "F", 6),
("Metapod", 3, "Mudar", NULL, 6),
("Butterfree", 5, "Ojo Compuesto", NULL, 6),
("Pidgey", 5, "Tumbos", NULL, 7),
("Pidgeotto", 6, "Tumbos", NULL, 7),
("Pidgeot", 8, "Tumbos", NULL, 7),
("Ekans", 5, "Mudar", "F", 8),
("Arbok", 5, "Mudar", "M", 8),
("Pikachu", 9, "Electricidad Estatica", NULL, 9),
("Raichu", 8, "Electricidad Estatica", NULL, 9),
("Evee", 2, "Fuga", NULL, 3),
("Geodude", 5, " Cabeza Roca", "F", 10),
("Graveler", 6, " Cabeza Roca", "F", 10),
("Golem", 7, " Cabeza Roca", NULL, 10),
("Dratini", 5, "Mudar", NULL, 11),
("Dragonair", 6, "Mudar", NULL, 11),
("Dragonite", 7, "Mudar", NULL, 11),
("Machop", 2, "Agallas", "M", 1),
("Machoke", 3, "Agallas", NULL, 1),
("Machamp", 4, "Agallas", NULL, 1),
("Abra", 5, "Sincronia", NULL, 2),
("Kadabra", 6, "Sincronia", NULL, 2),
("Alakazam", 7, "Sincronia", "F", 2),
("Mewtwo", 9, "Presion", NULL, 1),
("Mew", 9, "Sincronia", NULL, 1),
("Gastly", 3, "Levitacion", NULL, 1),
("Haunter", 4, "Levitacion", "M", 1),
("Gengar", 5, "Cuerpo Maldito", NULL, 1),
("Magnemite", 3, "Iman", NULL, 1),
("Magneton", 4, "Iman", "F", 1),
("Voltorb", 6, "Insonorizar", NULL, 1),
("Electrode", 7, "Insonorizar", NULL, 1),
("Exeggcute", 8, "Clorofila", "M", 1),
("Exeggutor", 9, "Clorofila", "F", 1),
("Lapras", 3, "Caparazon", NULL, 7);