INSERT INTO Tipo ( Nombre) VALUES
("AGUA"),                           
("FUEGO"),                          
("ELECTRICO"),                      
("NORMAL"),                         
("TIERRA"),  
("DRAGON"),                         
("VOLADOR"),                        
("HIELO"),                          
("LUCHA"),                          
("BICHO"),                          
("PSIQUICO"),                       
("FANTASMA"),                       
("VENENO"),                         
("PLANTA"),                         
("ROCA"),                               
("ACERO");  